# Generated by Django 3.1.3 on 2020-11-17 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Некорректные входные данные username', regex='^[\\w.@+-]+$')])),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Некорректные входные данные password', regex='^(?=.*[A-Z])(?=.*\\d).{8,}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField()),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
    ]
